### ISSUE TITLE
宝贝，你这个是ssr么，还是ss？？

### ISSUE THREAD

**Issue by themass** [victor8886/shadowsockr-java#15]
宝贝，你这个是ssr么，还是ss？？

**Comment by themass** [comment]
unsupported addrtype 69, maybe wrong password or encryption method
参数没问题，pc可以用

**Comment by victor8886** [comment]
ssr

**Comment by victor8886** [comment]
兼容ss

**Comment by themass** [comment]
你好，显示已连接，但是根本没成功，翻不了
 private String protocol = "auth_chain_a";
    private String protocol_param = "";
    private String obfs = "plain";
    private String obfs_param = "";
    private String method = "aes-128-ctr";

**Comment by themass** [comment]
unsupported addrtype 69, maybe wrong password or encryption method
