### ISSUE TITLE
线程阻塞

### ISSUE THREAD

**Issue by PlexPt** [victor8886/shadowsockr-java#8]
开启1像素的activity会导致主线程阻塞，
建议SDK手动传入activity

**Comment by victor8886** [comment]
当初就是考虑做个封装，这个activity的目的是利用activity的回调方法开启VPN.
可以添加个回调接口，这样就不用传递activity了

**Comment by PlexPt** [comment]
阻塞比麻烦好？

**Comment by victor8886** [comment]
可以把开启vpn的代码挪到自己的页面去，这样就好了
