### ISSUE TITLE
在编译jni的遇到的问题

### ISSUE THREAD

**Issue by alroyso** [victor8886/shadowsockr-java#9]
[armeabi-v7a] Executable     : libpdnsd.so
/Users/alroyso/Downloads/android-ndk-r12b/platforms/android-16/arch-arm/usr/lib/../lib/crtbegin_dynamic.o:crtbrand.c:function _start: error: undefined reference to 'main'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/armeabi-v7a/libpdnsd.so] Error 1

**Comment by victor8886** [comment]
ndk版本过低造成的
